### ISSUE TITLE
Notebook crash when rerun with existing FITS files

### ISSUE THREAD

**Issue by pllim** [spacetelescope/acs-notebook#8]
I was re-running `acs_destripe_plus` notebook to test the changes, but it crashed when it attempted to overwrite existing FITS file. Either clarify in the notebook that user need to remove existing files or gracefully handle the situation.

**Comment by tddesjardins** [comment]
I've added try except blocks to all of the notebooks when using `shutil.move` to grab data from the mastDownload directory. It will now remove existing files before moving the freshly downloaded ones.
